env:
  - FOO=0
  - FOO=1
  - FOO=2
  - FOO=3
  - FOO=4
  - FOO=5
  - FOO=6
  - FOO=7
  - FOO=8
  - FOO=9
  - FOO=10
  - FOO=11
  - FOO=12
  - FOO=13
  - FOO=14
  - FOO=15
  - FOO=16
  - FOO=17
  - FOO=18
  - FOO=19
  - FOO=20
  - FOO=21
  - FOO=22
  - FOO=23
  - FOO=24
  - FOO=25
  - FOO=26
  - FOO=27
  - FOO=28
  - FOO=29

script: sleep 5

notifications:
  email: 
    recipients:
    - me@svenfuchs.com
    on_success: always
