language: shell
env:
  global: 
    FOO: 
      secure: "tcnGKmyB799YyviChTDpGvR/7Iei01mgB6NkVb/CTwnHxOikphnbwzTDnTVvKqXrCHEea/tp7rd/ip04QMGfb6NQgBylluiLjU3L89LF1sBMuHp1Y33J73BdoZokQ+b7WSDgCDwM/RsPJYoK8DNCuyGLHwd/pMFYlD6NwZq2XjwpIMZSaOPx57ZPaVgFMr4dILuN+Jo815VbkcgtLErtp7+dbsR4Ly2Vq3fAoFZOnTes5nBm8p5JoxfZ/NQh6BeHi9J2cB2I17sDmTnwBPU7rI60tyYEte1vqr6wiwBCoxAgnobpgwkYWLvlkiVWC3QRN9noJLIJuhzmhjhNVkYjGknGkHaJGgSwtRYSl7f3vTbgiyRqEEUBHr4HqBQcQ74s75RwPRpVVF64hzyL409OfHSleos1GYEKY7OZ9YNNFwuaynqHCGy1sifbgAXZjGusCe2GoiIP+suPcQysKjp1KJrZjW8ZHn1D/fvuiTk0OuqpqUE1VkJhw5sYrcH6dYIiOLcPk7F3ivg4D/fbAgd0TtDqT/iIoB1ZCAxv8iV1Cb7g624vB+6rBldW58Fj+beHsbNMstd1r28Suhylj5bJlGvhWfSHfjVvs3ggA0c3gH5dCJDmCS18mzBB8OcqPxfSUD7JGSVs8+GPI7zFi+tsQPLF/9QaNPfJMR2ipE+/eyg="
script: echo $FOO
notifications:
  email: false
  slack:
    rooms:
      - secure: "Jc1zk3ekAoe9Q0CnOCBJOttYcUdhv+6Oz8vrcub1Gw1e5HqkidOoGf2bVcl0J6w/R2fN5l9aonuTELM3h6D8Y56uXCo5c1RLTakM70uYj7/xHYXr2G16Nfckn4jM3cb/Woc0Q2Oz3vlIpgsLc7zXUGhNkkbHEjqVmGEcXN/YwJiuzKf/mAX6EywHKzMkVN1Azkm13HWXnNaY8FXdPEq38Wd14jFQedcZrMHZB6Tyt7PD2EON8Y76MmKtJX3wkKHN70HviIm71txUk7Ozjgx2TKX9aazJQ+r85XsPrL1HXRZyHL9YiGVdpkfHHWJv/TEj2EgVpRD7my11H8SbSlKkftXGL1EZVYQSOAjC9aekxg9jqz0cqWZsshf1j4wGptWoe3HBetpRknD+EEp7O5z8mNYtqkt5ZIkXfoDa2Wd6S2eLbf+OSjfgSfATZN6DlRfyqjZT6nGT17ETCOXGUeEvQres2zSeHXNuFaIkId47vJXYr1YniTA3hWl3dibXMKufwo3W9iqiNirWbgg1vgQZk3kGOvOG94hU94McL4dSfJzgaDMeOhtKbIJJcbHrdlhZ95R8huI/m+jKv09dcAwYxZeI46Sy64jHE6aPJ7fXE4qzIvUiym8BJoMh7KCaHDciqJPp+pjgbi/tqov2daEzYVf1HYzg6Hn0ql3PsCWfRzQ="
    # template: Whoop
