language: shell
jobs:
  allow_failures:
    - name: Allow Failures
    - name: Only Feature Branch Allow Failures
      if: branch != master
  include:
    - stage: Test (Allow Failures)
      name: Allow Failures
      script: exit 1
    - name: Only Feature Branch Allow Failures
      script: exit 1
    - stage: Deploy
      name: Deploy
      script: echo "DEPLOY FOR $TRAVIS_BRANCH"
