jobs:
  include:
    - if: env(WILLIAM) IS present
      name: This works
      script: true

    - if: env(WILLIAM) IS present
      name: This does not work
      env:
        - ANYTHING=HERE
      script: true
