{
   "language" : "perl",
   "perl" : [
      "5.26",
      "5.14"
   ],
   "script" : true,
   "install" : true,
   "jobs" : {
      "include" : [
         {
            "stage" : "merge",
            "script" : echo "job.include"
         }
      ]
   }
}
