language: shell

before_install:
- 'function write() { echo "$2" | sed "s/  //" > $1; chmod +x $name; }'
- |-
  write foo << EOF
  #/bin/bash
  echo foo
- |-
  write bar << EOF
  #/bin/bash
  echo bar


script:
- cat ./foo
- cat ./bar
- ./foo
- ./bar
