rvm:
  - 2.2.1
  - 1.9.3

matrix:
  allow_failure:
    - rvm: 1.9.3

script: "ruby -v | grep 2.2.1"

# notifications:
#   email:
#     on_success: always
#   webhooks: http://requestb.in/1bz2pcx1
    
