language: shell

before_install:
- function write() { name=$1; content=$2; echo "$1" | sed 's/  //' > $name; chmod +x $name; }
- |-
  write foo << EOF
  #/bin/bash
  echo foo
- |-
  write bar << EOF
  #/bin/bash
  echo bar


script:
- cat ./foo
- cat ./bar
- ./foo
- ./bar
