language: shell
env:
  global:
    - OFFICIAL_REPO_SLUG="DanySK/conrec"
jobs:
  include:
    - name: one
    - stage: deploy
      name: two
      if:  type != pull_request AND repo = env(OFFICIAL_REPO_SLUG)
