language: shell

env:
  global:
    - GLOBAL=true
  jobs:
    - ONE=one
    - TWO=two

stages:
  - name: two
    if: 'env(TWO) = two'
  - name: three
    if: 'NOT env(TWO) = two'

jobs:
  include:
    - stage: two
      name: two
    - stage: three
      name: three
