rvm:
  - 2.2
  - 1.9

matrix:
  allow_failures:
    - rvm: 1.9

script: "if ruby -v | grep 2.2; then true; else sleep 30; false; fi"

# notifications:
#   email:
#     on_success: always
#   webhooks: http://requestb.in/1bz2pcx1
    
