language: shell

env:
  global:
    - GLOBAL=true

stages:
  - name: one
    if: 'env(ONE) = one'
  - name: two
    if: 'NOT env(ONE) = one'

jobs:
  include:
    - stage: one
      name: one
    - stage: two
      name: two
