# foo: - kaputt &!"
# ..........................

script: true
notifications:
  # email:
  #   on_success: always
  # webhooks: http://requestb.in/1bz2pcx1
    
env:
 - FOO=0
 - FOO=1
 - FOO=2
 - FOO=3
 - FOO=4
 - FOO=5
 - FOO=7
 - FOO=8
 - FOO=9
 - FOO=10
 - FOO=11
 - FOO=12
 - FOO=13
 - FOO=14
 - FOO=15
 - FOO=17
 - FOO=18
 - FOO=19
 - FOO=20
 - FOO=21
 - FOO=22
 - FOO=23
 - FOO=24
 - FOO=25
 - FOO=27
 - FOO=28
 - FOO=29
 - FOO=30
 - FOO=31
 - FOO=32
 - FOO=33
 - FOO=34
 - FOO=35
 - FOO=37
 - FOO=38
 - FOO=39
 - FOO=40
 - FOO=41
 - FOO=42
 - FOO=43
 - FOO=44
 - FOO=45
 - FOO=47
 - FOO=48
 - FOO=49
