dist: xenial
language: go
go:
  - 1.13.x

install: true
script: true

env:
  - GO111MODULE=on

stages:
  - name: test
  - name: build
    if: branch = master AND fork = false AND type != pull_request
  - name: build manifest
    if: branch = master AND fork = false AND type != pull_request

jobs:
  include:
    - name: Unit testing
      stage: test
    - name: Verify operator image build
      if: branch != master OR fork = true OR type = pull_request
    - name: E2E testing
      if: fork = false
    - name: Build image on amd64
      stage: build
      os: linux
      arch: amd64
    - name: Build image on ppc64le
      os: linux
      arch: ppc64le
    - name: Build image on s390x
      os: linux
      arch: s390x
    - name: Verify manifest lists
      stage: build manifest
