dist: xenial

addons:
  postgresql: 11
  apt:
    update: true
    packages:
      - postgresql-11
      - postgresql-client-11

services:
  - postgresql

before_script:
  - cat /var/log/postgresql/postgresql-11-main.log
  - psql --version
  - psql -c 'CREATE DATABASE travis_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - curl -fs https://raw.githubusercontent.com/travis-ci/travis-migrations/master/db/main/structure.sql | psql travis_test
