language: bash
services: docker

env:
  matrix:
  - SOLR_VER="8.4.1" TAGS="${SOLR_VER},8.4,8,latest" TESTABC_ASD="1.2.3" TESTZXC="${TESTABC_ASD},4,5"
  - SOLR_VER=8.3.1 TAGS="${SOLR_VER},8.3"

script:
- echo "${SOLR_VER}"
- echo "${TAGS}"
- echo "${TESTABC_ASD}"
- echo "${TESTZXC}"
