language: shell

env:
  global:
  - MULTIPASS_RELEASE_BRANCH_PATTERN="^release/([0-9\.]+)$"
  - MULTIPASS_RELEASE_TAG_PATTERN="^v([0-9]+\.[0-9]+)\.[0-9]+$"

if: | 
  branch IN (staging, trying, master)
  OR branch ~= env(MULTIPASS_RELEASE_BRANCH_PATTERN)
  OR branch ~= env(MULTIPASS_RELEASE_TAG_PATTERN)
  OR type = pull_request

jobs:
  include:
    - name: one
    - name: two
      if: |
        repo = svenfuchs/test
               AND (type != pull_request
                    OR head_repo = repo)
